language: clojure
lein: 2.8.1
cache:
  directories:
    - $HOME/.m2
jdk:
  - oraclejdk9
  - oraclejdk8
  - openjdk11
  - openjdk10
  - openjdk9
  - openjdk8
env:
before_install:
  - if [ -f "${JAVA_HOME}/lib/security/cacerts" -a -w  "${JAVA_HOME}/lib/security/cacerts" ]; then rm "${JAVA_HOME}/lib/security/cacerts" && ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"; fi;
script:
    - lein test
branch: master